import { Footer, Header } from "@/components";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full min-h-screen flex flex-col justify-between">
          <Header />
          <div className="bg-[#2B2B2B]">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
